version: '3.7'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    depends_on:
      - db
    # restart: always
    stdin_open: true
    tty: true


  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=developer
      - MONGO_INITDB_ROOT_PASSWORD=developer
      - MONGODB_HOSTNAME=mongodb
    volumes:
      - mongodb_data_container:/data/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:8080
    environment:
      - NODE_ENV=development

volumes:
  mongodb_data_container:

