version: '3.7'
services:
  service-auth:
    container_name: service-auth
    build:
      context: ./backend/service-auth
      dockerfile: Dockerfile
    volumes:
      - ./backend/service-auth/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./backend/service-auth/.env
    depends_on:
      - db
    # restart: always
    stdin_open: true
    tty: true

  service-sor:
    container_name: service-sor
    build:
      context: ./backend/service-sor
      dockerfile: Dockerfile
    volumes:
      - ./backend/service-sor/:/usr/src/app/
    ports:
      - 5001:5001
    env_file:
      - ./backend/service-sor/.env
    depends_on:
      - db
    # restart: always
    stdin_open: true
    tty: true


  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=developer
      - MONGO_INITDB_ROOT_PASSWORD=developer
      - MONGODB_HOSTNAME=mongodb
    volumes:
      - mongodb_data_container:/data/db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:8080
    environment:
      - NODE_ENV=development

volumes:
  mongodb_data_container:

