version: "3.3"
services:
  # backend:
  #   image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
  #   ports:
  #     - "${BACKEND_API_PORT:-5000}:5000"
  #   volumes:
  #     - type: volume
  #       source: mongodb_data_container
  #       target: /data
    
  #   env_file:
  #     - .env
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile

  # frontend:
  #   image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
  #   ports:
  #     - 3000:3000
  #   build:
  #     context: ./frontend
  #     args:
  #       FRONTEND_ENV: ${FRONTEND_ENV-production}
    
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: developer
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

